-- Variables: week, id, id_municipio_receita, tipo, value_send, trans_send, value_rec, trans_rec, value_self, trans_self

WITH ID_list AS (
  SELECT firm_id14 AS id
  FROM DL_DEPEP_ESTABILIDADE_FINANCEIRA.Random_sample_Pix_Fin_Rev_PJ
),
MAIN_send AS (
    SELECT 
    	TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL
						        ELSE A.PEB_CD_CNPJ_CPF_PAGDR END) AS id,
        SUM(CASE WHEN A.BBC_VL_TIT > 0 THEN
		          CASE WHEN A.BBC_VL_BAIXA_EFT_TIT / A.BBC_VL_TIT > 10 THEN A.BBC_VL_TIT
		            ELSE A.BBC_VL_BAIXA_EFT_TIT END
		      ELSE A.BBC_VL_BAIXA_EFT_TIT END) AS valor,
        COUNT(A.BBC_VL_TIT) AS trans
    FROM CIPDWPRO_ACC.CIPTB_BBC_BOLETO_BAIXA_DIARIA_CIP AS A
    WHERE 
        A.DTE_DT_BASE_MVTO >= '@selectedDateSTART' AND A.DTE_DT_BASE_MVTO < '@selectedDateEND'
        AND A.PEB_CD_TP_PESSOA_PAGDR = 'J'
        AND (EXISTS(SELECT 1 FROM ID_list WHERE ID_list.id = TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL ELSE A.PEB_CD_CNPJ_CPF_PAGDR END)))
        AND A.PEB_CD_CNPJ_CPF_PAGDR <> 'N/I'
        AND TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL ELSE A.PEB_CD_CNPJ_CPF_PAGDR END) 
            <> TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_BENFCRIO_FINL = '' THEN A.PEB_CD_CNPJ_CPF_BENFCRIO_OR ELSE A.PEB_CD_CNPJ_CPF_BENFCRIO_FINL END)
    GROUP BY id
),
MAIN_rec AS (
    SELECT 
      TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_BENFCRIO_FINL = '' THEN A.PEB_CD_CNPJ_CPF_BENFCRIO_OR
			              ELSE A.PEB_CD_CNPJ_CPF_BENFCRIO_FINL END) AS id,      
        SUM(CASE WHEN A.BBC_VL_TIT > 0 THEN
		      CASE WHEN A.BBC_VL_BAIXA_EFT_TIT / A.BBC_VL_TIT > 10 THEN A.BBC_VL_TIT
		      ELSE A.BBC_VL_BAIXA_EFT_TIT END
		    ELSE A.BBC_VL_BAIXA_EFT_TIT END) AS valor,
        COUNT(A.BBC_VL_TIT) AS trans
    FROM CIPDWPRO_ACC.CIPTB_BBC_BOLETO_BAIXA_DIARIA_CIP AS A
    WHERE 
        A.DTE_DT_BASE_MVTO >= '@selectedDateSTART' AND A.DTE_DT_BASE_MVTO < '@selectedDateEND'
        AND COALESCE(A.PEB_CD_TP_PESSOA_BENFCRIO_FINL, A.PEB_CD_TP_PESSOA_BENFCRIO_OR) ='J'
        AND (EXISTS(SELECT 1 FROM ID_list WHERE ID_list.id = TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_BENFCRIO_FINL = '' THEN A.PEB_CD_CNPJ_CPF_BENFCRIO_OR ELSE A.PEB_CD_CNPJ_CPF_BENFCRIO_FINL END)))
        AND TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL ELSE A.PEB_CD_CNPJ_CPF_PAGDR END) 
            <> TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_BENFCRIO_FINL = '' THEN A.PEB_CD_CNPJ_CPF_BENFCRIO_OR ELSE A.PEB_CD_CNPJ_CPF_BENFCRIO_FINL END)
    GROUP BY id
),
MAIN_self AS (
    SELECT 
    	TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL
						        ELSE A.PEB_CD_CNPJ_CPF_PAGDR END) AS id,
        SUM(CASE WHEN A.BBC_VL_TIT > 0 THEN
		          CASE WHEN A.BBC_VL_BAIXA_EFT_TIT / A.BBC_VL_TIT > 10 THEN A.BBC_VL_TIT
		            ELSE A.BBC_VL_BAIXA_EFT_TIT END
		      ELSE A.BBC_VL_BAIXA_EFT_TIT END) AS valor,
        COUNT(A.BBC_VL_TIT) AS trans
    FROM CIPDWPRO_ACC.CIPTB_BBC_BOLETO_BAIXA_DIARIA_CIP AS A
    WHERE 
        A.DTE_DT_BASE_MVTO >= '@selectedDateSTART' AND A.DTE_DT_BASE_MVTO < '@selectedDateEND'
        AND A.PEB_CD_TP_PESSOA_PAGDR = 'J'
        AND (EXISTS(SELECT 1 FROM ID_list WHERE ID_list.id = TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL ELSE A.PEB_CD_CNPJ_CPF_PAGDR END)))
        AND A.PEB_CD_CNPJ_CPF_PAGDR <> 'N/I'
        AND TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_PAGDR = '' THEN NULL ELSE A.PEB_CD_CNPJ_CPF_PAGDR END) 
            = TO_NUMBER(CASE WHEN A.PEB_CD_TP_PESSOA_BENFCRIO_FINL = '' THEN A.PEB_CD_CNPJ_CPF_BENFCRIO_OR ELSE A.PEB_CD_CNPJ_CPF_BENFCRIO_FINL END)
    GROUP BY id
)
SELECT
    @WEEK as week,
    2 AS tipo,
    ID_list.id AS id,
    COALESCE(MAIN_send.valor, 0) AS value_send,
    COALESCE(MAIN_send.trans, 0) AS trans_send,
    COALESCE(MAIN_rec.valor, 0) AS value_rec,
    COALESCE(MAIN_rec.trans, 0) AS trans_rec,
    COALESCE(MAIN_self.valor, 0) AS value_self,
    COALESCE(MAIN_self.trans, 0) AS trans_self
FROM ID_list 
LEFT JOIN MAIN_send ON (MAIN_send.id = ID_list.id)
LEFT JOIN MAIN_rec ON (MAIN_rec.id = ID_list.id)
LEFT JOIN MAIN_self ON (MAIN_self.id = ID_list.id)

-- Variables: week, id, tipo, value_send, trans_send, value_rec, trans_rec, value_self, trans_self