-- Accounts closing (CCS) por Municipio x IF 


  SELECT
    COUNT(DISTINCT REL_CD_CPF_CNPJ) AS closing,
    PAR_CD_CNPJ_PAR AS bank, 
    RFB.MUN_CD AS id_municipio_receita,
    REL_CD_TIPO_PESSOA AS tipo,
    @WEEK AS week
  FROM CCSDWPRO_ACC.CCSTB_FRE_FATO_RELACIONAMENTO AS CCS
  LEFT JOIN BCBDWPRO_ACC.PESTB_PEJ_PESSOA_JURIDICA AS RFB 
    ON TO_NUMBER(CCS.REL_CD_CPF_CNPJ) = TO_NUMBER(RFB.PEJ_CD_CNPJ14)
  WHERE 
    REL_CD_TIPO_PESSOA = 2 AND
    REL_DT_FIM >= TO_DATE('@selectedDateSTART', 'YYYY-MM-DD') AND REL_DT_FIM < TO_DATE('@selectedDateEND', 'YYYY-MM-DD')
  GROUP BY RFB.MUN_CD, PAR_CD_CNPJ_PAR, REL_CD_TIPO_PESSOA
