-- id_information_PF

SELECT
  RNDSAMPLE.CPF_CD AS id,    
  RFB.MUN_CD AS id_municipio_receita
FROM 
  DL_DEPEP_ESTABILIDADE_FINANCEIRA.Random_sample_Pix_Fin_Rev as RNDSAMPLE
  INNER JOIN BCBDWPRO_ACC.PESTB_PEF_PESSOA_FISICA AS RFB 
  ON RNDSAMPLE.CPF_CD = RFB.PEF_CD_CPF;