-- id_information_PJ

SELECT
  RNDSAMPLE.firm_id14 AS id,
  RFB.MUN_CD AS id_municipio_receita
FROM 
  DL_DEPEP_ESTABILIDADE_FINANCEIRA.Random_sample_Pix_Fin_Rev_PJ AS RNDSAMPLE
  INNER JOIN BCBDWPRO_ACC.PESTB_PEJ_PESSOA_JURIDICA AS RFB
  ON RNDSAMPLE.firm_id14 = TO_NUMBER(RFB.PEJ_CD_CNPJ14);