-- Bank Flow and Use.

WITH PercentileData_rec AS (
  SELECT
    LAF_VL,
    PERCENT_RANK() OVER (PARTITION BY TPP_CD_TIPO_PESSOA_RECEBEDOR ORDER BY LAF_VL) AS PercentileRank,
    TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo
  FROM PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO
  WHERE 
    STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
),
Limits_rec1(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData_rec
WHERE tipo=1
),
Limits_rec2(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData_rec
WHERE tipo=2
)
-- # Variables: week, muni_cd, tipo, bank,  send_users, rec_users, value_send, trans_send, value_send_w, value_rec, trans_rec,  value_rec_w
SELECT	
    @WEEK AS week,
    CLI_REC.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_RECEBEDOR_ATUAL AS bank,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_RECEBEDOR) AS rec_users,
    SUM(LAF_VL) as value_rec, 
    COUNT(LAF_VL) as trans_rec,
    SUM(CASE
        WHEN PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits_rec1.high THEN Limits_rec1.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits_rec2.high THEN Limits_rec2.high
                ELSE LAF_VL
            END
    END) AS value_rec_w
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD), Limits_rec1, Limits_rec2
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
GROUP BY
    CLI_REC.MUN_CD,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_RECEBEDOR_ATUAL,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR;
