-- Bank_Muni

-- For boleto PEB_CD_CNPJ_CPF_PORT [VARCHAR(14) LATIN] maybe represents the bank

--            ,<PAT_CD_CPF_CNPJ_REC, varchar(14),> for ted sitraf. 
--           ,<PAT_CD_CPF_CNPJ_REM, varchar(14),>
-- ,<PAT_CD_CPF_CNPJ_INSS, varchar(14),>???????
--            ,<PAL_CD_ISPB_CRD, char(8),>??
--           ,<PAL_CD_ISPB_DEB, char(8),>??


-- debit and credit, which bank received the money?
-- DEB_CD_CNPJ_BASECREDDR [CHAR(8) LATIN Not Null], DEB_CD_CNPJ_CPF_PONTOVENDA [CHAR(14) LATIN Not Null],
--    DEB_CD_CNPJ8_CPF11_PONTOVENDA [CHAR(11) LATIN], DEB_CD_CNPJ_CREDDR [CHAR(14) LATIN],
--    DEB_CD_ISPB_IF_DEVDR [CHAR(8) LATIN], DEB_CD_ISPB_IF_CREDR [CHAR(8) LATIN],

-- credito

-- ccs

WITH Pix_Senders_id AS (
SELECT	
    CLI_PAG.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS tipo,
    PIX.PES_NU_CPF_CNPJ_PAGADOR AS id,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_PAGADOR_ATUAL AS bank,
    PIX.PES_NU_CPF_CNPJ_PAGADOR AS id_sender,
    0 AS id_receiver
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
GROUP BY
    CLI_PAG.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.PES_NU_CPF_CNPJ_PAGADOR,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_PAGADOR_ATUAL
),
Pix_Receivers_id AS (
SELECT	
    CLI_REC.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo,
    PIX.PES_NU_CPF_CNPJ_RECEBEDOR AS id,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_RECEBEDOR_ATUAL AS bank,
    0 AS id_sender,
    PIX.PES_NU_CPF_CNPJ_RECEBEDOR AS id_receiver
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
GROUP BY
    CLI_REC.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR,
    PIX.PES_NU_CPF_CNPJ_RECEBEDOR,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_RECEBEDOR_ATUAL
)
SELECT	
    @WEEK AS week, 
    muni_cd,
    tipo,
    bank,
    COUNT(DISTINCT id) AS users,
    COUNT(DISTINCT id_sender) AS senders,
    COUNT(DISTINCT id_receiver) AS receivers
FROM (SELECT * FROM Pix_Senders_id UNION ALL SELECT * FROM Pix_Receivers_id) AS CombinedData
GROUP BY 
  muni_cd, tipo, bank;
