-- Pix_Muni_user
-- # Variables: week, muni_cd, tipo, users

WITH Senders_id AS (
SELECT	
    CLI_PAG.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS tipo,
    PIX.PES_NU_CPF_CNPJ_PAGADOR AS id
    --PIX.PES_NU_CPF_CNPJ_PAGADOR AS id_sender
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
    LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR as CLI_PAG 
    ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
    LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR as CLI_REC 
    ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    --AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
GROUP BY
    CLI_PAG.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.PES_NU_CPF_CNPJ_PAGADOR
),
Receivers_id AS (
SELECT	
    CLI_REC.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo,
    PIX.PES_NU_CPF_CNPJ_RECEBEDOR AS id
    --PIX.PES_NU_CPF_CNPJ_RECEBEDOR AS id_receiver
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
    LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR as CLI_PAG 
    ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
    LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR as CLI_REC 
    ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    --AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
GROUP BY
    CLI_REC.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR,
    PIX.PES_NU_CPF_CNPJ_RECEBEDOR
)
SELECT	
    @WEEK AS week, 
    muni_cd,
    tipo,
    COUNT(DISTINCT id) AS users
    --COUNT(DISTINCT id_sender) AS senders,
    --COUNT(DISTINCT id_receiver) AS receivers
FROM (SELECT * FROM Senders_id UNION ALL SELECT * FROM Receivers_id) AS CombinedData
GROUP BY 
  muni_cd, tipo;

