-- Bank Flow and Use.

WITH PercentileData_send AS (
  SELECT
    LAF_VL,
    PERCENT_RANK() OVER (PARTITION BY TPP_CD_TIPO_PESSOA_PAGADOR ORDER BY LAF_VL) AS PercentileRank,
    TPP_CD_TIPO_PESSOA_PAGADOR AS tipo
  FROM PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO
  WHERE 
    STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
),
Limits_send1(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData_send
WHERE tipo=1
),
Limits_send2(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData_send
WHERE tipo=2
)
SELECT	
    @WEEK AS week,
    CLI_PAG.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS tipo,
    PAT_CD_CNPJ_PARTICIPANTE_PAGADOR_ATUAL AS bank,
    SUM(LAF_VL) as value_send, 
    COUNT(LAF_VL) as trans_send,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_PAGADOR) AS send_users,
    SUM(CASE
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits_send1.high THEN Limits_send1.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits_send2.high THEN Limits_send2.high
                ELSE LAF_VL
            END
    END) AS value_send_w
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD), Limits_send1, Limits_send2
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
GROUP BY
    CLI_PAG.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.PAT_CD_CNPJ_PARTICIPANTE_PAGADOR_ATUAL;