COLLECT STATISTICS COLUMN (ID_REC), 
				   COLUMN (ID_SEND),
				   COLUMN (ID_SEND, ID_REC),
				   COLUMN (LIF_CD_TP_PES_CRED),
				   COLUMN (LIF_CD_TP_PES_DEB),
				   COLUMN (LIF_CD_TP_PES_CRED, LIF_CD_TP_PES_DEB),
				   COLUMN (LIF_CD_NUM_OPER) ON "depep.jrenato".VT_tableSTRDetails;


