-- TED_STR_(Volatil) 
CREATE MULTISET VOLATILE TABLE "depep.jrenato".VT_tableSTRDetails, NO LOG 
AS (
SELECT 
    TRYCAST(tableSTRDetails.LIF_CD_CNPJCPFDEB1 AS BIGINT) AS id_send,
    TRYCAST(tableSTRDetails.LIF_CD_CNPJCPFCRE1 AS BIGINT) AS id_rec,
    LIF_CD_NUM_OPER 
FROM
	STRDWPRO_ACC.STRTB_LIF_LAN_IF AS tableSTRDetails
WHERE	
	LIF_CD_TP_PES_CRED = '@TIPO_REC' 
    AND LIF_CD_TP_PES_DEB = '@TIPO_SEND'
	)
WITH DATA PRIMARY INDEX (ID_SEND, ID_REC) ON COMMIT PRESERVE ROWS;
--Elapsed time = 00:25:51.367 


