-- Adoption

WITH FirstReceive AS (
  SELECT
      PES_NU_CPF_CNPJ_RECEBEDOR as id,
      MIN(LAF_DT_LIQUIDACAO) as dia,
      CLI_REC.MUN_CD as muni_cd,
      TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo
  FROM  
    DL_DEPEP_ESTABILIDADE_FINANCEIRA.Random_sample_Pix_Fin_Rev as RNDSAMPLE
    LEFT JOIN	PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX 
    ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = RNDSAMPLE.CPF_CD)
    LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC 
    ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
  WHERE
    	STA_CD_LIQUIDADA = 'S'
    	AND STA_CD_REJEICAO = 'N'
      AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
      AND TPP_CD_TIPO_PESSOA_RECEBEDOR = 1
  GROUP BY
      PES_NU_CPF_CNPJ_RECEBEDOR,
      CLI_REC.MUN_CD,
      TPP_CD_TIPO_PESSOA_RECEBEDOR
)
  SELECT dia, muni_cd, COUNT(id) AS rec_adopters, tipo
  FROM FirstReceive
  GROUP BY dia, muni_cd, tipo
