-- Debit_card_rec_adoption

WITH debit AS (
SELECT
  DEB_CD_CNPJ_CPF_PONTOVENDA AS id,
  --DEB_CD_CNPJ8_CPF11_PONTOVENDA AS id,
  MIN(DEB_DT_DT_PGTO) AS dia,
  DEB_CD_TP_PESSOA_PONTOVENDA as tipo,
  DEB_MUN_IBGE_CD_PONTOVENDA as id_municipio
FROM EACDWPRO_ACC.EAC_DEB_DEBITO_TGT
WHERE 
  DEB_CD_SIT_SOLICTCLIQUID IN (5,6,7) AND 
  DEB_CD_SITUACAO_RESPINSTDOMCL NOT IN ('002', '006') --filtros CIP (notar 6 e não 3 no respinstdomcl)
  AND DEB_MUN_IBGE_CD_PONTOVENDA = @MUNI_CD_LOOP
GROUP BY
  DEB_MUN_IBGE_CD_PONTOVENDA,
  DEB_CD_TP_PESSOA_PONTOVENDA,
  --DEB_CD_CNPJ8_CPF11_PONTOVENDA
  DEB_CD_CNPJ_CPF_PONTOVENDA
)
SELECT
  id_municipio,
  tipo,
  COUNT(DISTINCT id) AS adopters,
  dia
FROM debit
GROUP BY id_municipio,  tipo, dia;

