

-- Variables:  NU_CPF, NU_NIS, NOME_BENEFICIARIO, UF, IBGE_MUNICIPIO, NOME_MUNICIPIO, NO_GRUPO_PGTO, NU_PARCELA, IN_MONOPARENTAL, VL_RECEBIDO, ANOMES_CREDITO
SELECT NU_CPF, NU_NIS, NO_GRUPO_PGTO, ANOMES_CREDITO
FROM dl_depep_cadunico.aux_emergencial_20220107
WHERE ANOMES_CREDITO = 202104
GROUP BY NU_CPF, NU_NIS, NO_GRUPO_PGTO, ANOMES_CREDITO