-- Pix Flows

WITH PercentileData AS (
  SELECT
    LAF_VL,
    PERCENT_RANK() OVER (PARTITION BY TPP_CD_TIPO_PESSOA_PAGADOR, TPP_CD_TIPO_PESSOA_RECEBEDOR ORDER BY LAF_VL) AS PercentileRank,
    TPP_CD_TIPO_PESSOA_PAGADOR AS tipo_send,
    TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo_rec
  FROM PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO
  WHERE 
    STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
),
Limits11(high) AS (
SELECT MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData
WHERE tipo_send=1 AND tipo_rec=1
),
Limits12(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData
WHERE tipo_send=1 AND tipo_rec=2
),
Limits21(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData
WHERE tipo_send=2 AND tipo_rec=1
),
Limits22(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData
WHERE tipo_send=2 AND tipo_rec=2
),
Inflow AS (
SELECT	
    1 AS flow_code,
    @WEEK AS week, 
    CLI_REC.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS sender_type,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS receiver_type,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_PAGADOR) AS senders,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_RECEBEDOR) AS receivers,
    SUM(LAF_VL) as valor, 
    COUNT(LAF_VL) as trans,
    SUM(CASE
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits11.high THEN Limits11.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits12.high THEN Limits12.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits21.high THEN Limits21.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits22.high THEN Limits22.high
                ELSE LAF_VL
            END
    END) AS valor_w
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD), Limits11, Limits12, Limits21, Limits22
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND CLI_PAG.MUN_CD <> CLI_REC.MUN_CD
GROUP BY
    CLI_REC.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR
),
Outflow AS (
SELECT	
    -1 AS flow_code,
    @WEEK AS week, 
    CLI_PAG.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS sender_type,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS receiver_type,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_PAGADOR) AS senders,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_RECEBEDOR) AS receivers,
    SUM(LAF_VL) as valor, 
    COUNT(LAF_VL) as trans,
    SUM(CASE
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits11.high THEN Limits11.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits12.high THEN Limits12.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits21.high THEN Limits21.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits22.high THEN Limits22.high
                ELSE LAF_VL
            END
    END) AS valor_w
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD), Limits11, Limits12, Limits21, Limits22
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND CLI_PAG.MUN_CD <> CLI_REC.MUN_CD
GROUP BY
    CLI_PAG.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR
),
Intra AS (
SELECT	
    0 AS flow_code,
    @WEEK AS week, 
    CLI_REC.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS sender_type,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS receiver_type,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_PAGADOR) AS senders,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_RECEBEDOR) AS receivers,
   -- COUNT(DISTINCT (PIX.PES_NU_CPF_CNPJ_PAGADOR , PIX.PES_NU_CPF_CNPJ_RECEBEDOR) ) AS users,
    SUM(LAF_VL) as valor, 
    COUNT(LAF_VL) as trans,
    SUM(CASE
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits11.high THEN Limits11.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 1 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits12.high THEN Limits12.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits21.high THEN Limits21.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR = 2 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits22.high THEN Limits22.high
                ELSE LAF_VL
            END
    END) AS valor_w
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD), Limits11, Limits12, Limits21, Limits22
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND CLI_PAG.MUN_CD = CLI_REC.MUN_CD
GROUP BY
    CLI_REC.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR
),
PercentileData_self AS (
  SELECT
    LAF_VL,
    PERCENT_RANK() OVER (PARTITION BY TPP_CD_TIPO_PESSOA_RECEBEDOR ORDER BY LAF_VL) AS PercentileRank,
    TPP_CD_TIPO_PESSOA_RECEBEDOR AS tipo
  FROM PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO
  WHERE 
    STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR = PES_NU_CPF_CNPJ_PAGADOR
    AND LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
),
Limits1(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData_self
WHERE tipo=1
),
Limits2(high) AS (
SELECT  MIN(CASE WHEN PercentileRank >= 0.95 THEN LAF_VL END)
FROM PercentileData_self
WHERE tipo=2
),
Self AS (
SELECT	
    99 AS flow_code,
    @WEEK AS week, 
    CLI_REC.MUN_CD AS muni_cd,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS receiver_type,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_RECEBEDOR) AS users,
    SUM(LAF_VL) as valor, 
    COUNT(LAF_VL) as trans,
    SUM(CASE
        WHEN PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 1 THEN
            CASE
                WHEN LAF_VL > Limits1.high THEN Limits1.high
                ELSE LAF_VL
            END
        WHEN PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = 2 THEN
            CASE
                WHEN LAF_VL > Limits2.high THEN Limits2.high
                ELSE LAF_VL
            END
    END) AS valor_w
FROM
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD), Limits1, Limits2
WHERE
    LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
  	AND STA_CD_LIQUIDADA = 'S'
  	AND STA_CD_REJEICAO = 'N'
    AND PES_NU_CPF_CNPJ_RECEBEDOR = PES_NU_CPF_CNPJ_PAGADOR
GROUP BY
    CLI_REC.MUN_CD,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR
)

SELECT * FROM Inflow
UNION ALL
SELECT * FROM Outflow
UNION ALL
SELECT * FROM Intra
UNION ALL
SELECT * FROM Self;
