-- Pix_adoption_PJ

WITH IDs AS (
  SELECT 
    PEG_CD_CPF_CNPJ14 AS id,
    TPE_CD AS tipo,
    MUN_CD AS muni_cd
  FROM
    PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR
  WHERE MUN_CD = @MUNI_CD_LOOP AND TPE_CD = 2
),
MAIN AS (
  SELECT
      (CASE WHEN CLI_PAG.muni_cd IS NOT NULL THEN PIX.PES_NU_CPF_CNPJ_PAGADOR
        ELSE NULL END) AS id_send,
      (CASE WHEN CLI_REC.muni_cd IS NOT NULL THEN PIX.PES_NU_CPF_CNPJ_RECEBEDOR
        ELSE NULL END) AS id_rec,
      (CASE WHEN CLI_PAG.muni_cd IS NOT NULL THEN PIX.TPP_CD_TIPO_PESSOA_PAGADOR
        ELSE NULL END) AS tipo_send,
      (CASE WHEN CLI_REC.muni_cd IS NOT NULL THEN PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR
        ELSE NULL END) AS tipo_rec,
      ((EXTRACT(YEAR FROM PIX.LAF_DT_LIQUIDACAO)-1960)*12 
        + EXTRACT(MONTH FROM PIX.LAF_DT_LIQUIDACAO)) AS time_id
  FROM 
    PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
    LEFT JOIN IDs CLI_PAG 
    ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.id AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.tipo)
    LEFT JOIN IDs CLI_REC 
    ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.id AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.tipo)
  WHERE
    	PIX.STA_CD_LIQUIDADA = 'S'
    	AND PIX.STA_CD_REJEICAO = 'N'
      AND (CLI_PAG.muni_cd IS NOT NULL OR CLI_REC.muni_cd IS NOT NULL)
      AND PIX.LAF_DT_LIQUIDACAO < '2023-01-01'
),
Adoption AS (
SELECT
    id,
    tipo,
    MIN(time_id) AS time_id
FROM (SELECT id_send AS id, tipo_send AS tipo, time_id FROM MAIN UNION ALL SELECT id_rec AS id, tipo_rec AS tipo, time_id FROM MAIN) AS Combined2
GROUP BY 
  id, tipo
)
SELECT 
  time_id, 
  tipo,
  COUNT(id) AS adopters, 
  @MUNI_CD_LOOP as muni_cd
FROM Adoption
GROUP BY time_id, tipo
