-- PIX para si mesmo
SELECT	

LAF_DT_LIQUIDACAO as DIA, 
SUM(LAF_VL) as VALOR_SELF, 
COUNT(LAF_VL) as QTD_SELF,
COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_PAGADOR)   as n_cli_self,
CLI_PAG.MUN_CD as MUN_CD,
TPP_CD_TIPO_PESSOA_PAGADOR as tipo_pessoa

FROM	PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG
ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND  PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC
ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND  PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)


WHERE
  LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
	AND STA_CD_LIQUIDADA = 'S'
	AND STA_CD_REJEICAO = 'N'
  AND PES_NU_CPF_CNPJ_RECEBEDOR = PES_NU_CPF_CNPJ_PAGADOR
  AND CLI_PAG.MUN_CD = CLI_REC.MUN_CD
  
GROUP BY LAF_DT_LIQUIDACAO, CLI_PAG.MUN_CD, PIX.TPP_CD_TIPO_PESSOA_PAGADOR


