-- Pix for Others - PAGADOR
-- Agregando por mes
-- Amostra 2M

-- This left join is kinda wrong, since it is actually a inner join. Those that never did pix are not in the PIX data so we dont have their municipality. 
SELECT	
PES_NU_CPF_CNPJ_PAGADOR as id,
SUM(LAF_VL) as value_sent,
COUNT(LAF_VL) as trans_sent,
CLI_PAG.MUN_CD as muni_cd
FROM  DL_DEPEP_ESTABILIDADE_FINANCEIRA.Random_sample_Pix_Fin_Rev as RNDSAMPLE
LEFT JOIN	PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = RNDSAMPLE.CPF_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_PAG
ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND  PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)

WHERE
  PES_NU_CPF_CNPJ_PAGADOR <> PES_NU_CPF_CNPJ_RECEBEDOR
  AND TPP_CD_TIPO_PESSOA_PAGADOR = 1
  AND LAF_DT_LIQUIDACAO >= DATE '@selectedDateSTART'AND LAF_DT_LIQUIDACAO < DATE '@selectedDateEND'
	AND STA_CD_LIQUIDADA = 'S'
	AND STA_CD_REJEICAO = 'N'
GROUP BY PES_NU_CPF_CNPJ_PAGADOR, CLI_PAG.MUN_CD
