-- Pix for Others - RECEBEDOR
-- Agregando por mes
-- Amostra 2M
SELECT	
PES_NU_CPF_CNPJ_RECEBEDOR as id,
SUM(LAF_VL) as value_rec,
COUNT(LAF_VL) as trans_rec,
CLI_REC.MUN_CD as muni_cd
FROM  DL_DEPEP_ESTABILIDADE_FINANCEIRA.Random_sample_Pix_Fin_Rev as RNDSAMPLE
LEFT JOIN	PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = RNDSAMPLE.CPF_CD)
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC
ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND  PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)

WHERE
  PES_NU_CPF_CNPJ_PAGADOR <> PES_NU_CPF_CNPJ_RECEBEDOR
  AND TPP_CD_TIPO_PESSOA_RECEBEDOR = 1
  AND LAF_DT_LIQUIDACAO >= DATE '@selectedDateSTART'AND LAF_DT_LIQUIDACAO < DATE '@selectedDateEND'
	AND STA_CD_LIQUIDADA = 'S'
	AND STA_CD_REJEICAO = 'N'
GROUP BY PES_NU_CPF_CNPJ_RECEBEDOR, CLI_REC.MUN_CD
