SELECT	LAF_DT_LIQUIDACAO as DIA, 
SUM(LAF_VL) as VALOR, 
COUNT(LAF_VL) as QTD,
CLI_REC.MUN_CD as MUN_REC
FROM	PIXDWPRO_ACC.SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR CLI_REC
ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND  PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
WHERE
  LAF_DT_LIQUIDACAO >= @selectedDateSTART AND LAF_DT_LIQUIDACAO < @selectedDateEND
	AND STA_CD_LIQUIDADA = 'S'
	AND STA_CD_REJEICAO = 'N'
  AND PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
GROUP BY LAF_DT_LIQUIDACAO, 
CLI_REC.MUN_CD

