-- Estoque de contas (CCS) por Municipio x IF 
SELECT	
COUNT(REL_CD_CPF_CNPJ) as QTD,
PAR_CD_CNPJ_PAR AS instituicao, 
RFB.MUN_CD as muni_cd
FROM	CCSDWPRO_ACC.CCSTB_FRE_FATO_RELACIONAMENTO as CCS
LEFT JOIN PIXDWPRO_ACC.SPIVW_PES_PESSOA_FIS_JUR as RFB
ON CCS.REL_CD_CPF_CNPJ = TO_NUMBER(RFB.PEG_CD_CPF_CNPJ14)
WHERE 
REL_CD_TIPO_PESSOA = 1 AND
REL_DT_INICIO <= TO_DATE('@selectedDate','YYYY-MM-DD')    AND 
(REL_DT_FIM > TO_DATE('@selectedDate','YYYY-MM-DD')  OR REL_ST_STATUS_RELACIONAMENTO = 'A')
GROUP BY RFB.MUN_CD,PAR_CD_CNPJ_PAR


