
-- inflow
-- NEED LowerLimit and UpperLimit from winsorize.sql
SELECT	
    PIX.LAF_DT_LIQUIDACAO as DIA, 
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR AS pag_tipo,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR AS rec_tipo,
    1 AS flow_code,
    SUM(LAF_VL) as VALOR, 
    COUNT(LAF_VL) as QTD,
    SUM(
        CASE
            WHEN LAF_VL < 50 THEN 50
            WHEN LAF_VL > 51 THEN 51
            ELSE LAF_VL
        END
    ) AS VALOR_WINSORIZED,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_PAGADOR) AS senders,
    COUNT(DISTINCT PIX.PES_NU_CPF_CNPJ_RECEBEDOR) AS receivers
FROM
    SPITB_LAF_LANCAMENTO_FATO PIX
LEFT JOIN SPIVW_PES_PESSOA_FIS_JUR CLI_PAG ON (PIX.PES_NU_CPF_CNPJ_PAGADOR = CLI_PAG.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_PAGADOR = CLI_PAG.TPE_CD)
LEFT JOIN SPIVW_PES_PESSOA_FIS_JUR CLI_REC ON (PIX.PES_NU_CPF_CNPJ_RECEBEDOR = CLI_REC.PEG_CD_CPF_CNPJ14 AND PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR = CLI_REC.TPE_CD)
WHERE
    PES_NU_CPF_CNPJ_RECEBEDOR <> PES_NU_CPF_CNPJ_PAGADOR
    AND CLI_PAG.MUN_CD <> CLI_REC.MUN_CD
GROUP BY
    CLI_REC.MUN_CD,
    PIX.LAF_DT_LIQUIDACAO,
    PIX.TPP_CD_TIPO_PESSOA_PAGADOR,
    PIX.TPP_CD_TIPO_PESSOA_RECEBEDOR
